import type { AgentActivityPayload } from './ws'

export interface InvestigationTracePanelProps {
  activity: AgentActivityPayload[]
  busy: boolean
  hasChain: boolean
}

type StepStatus = 'pending' | 'ok' | 'empty' | 'error' | 'info'

interface TraceStep {
  key: string
  kind: 'tool' | 'done' | 'thinking' | 'error'
  label: string
  tool?: string
  source?: string
  detail?: string
  status: StepStatus
}

// foldActivity collapses the raw call/result stream into one row per tool call:
// a tool_call opens a pending step, the matching tool_result (same tool, most
// recent still-pending) completes it. done/thinking/error events render as
// their own rows. Tool names are disjoint across the two agents, so matching on
// tool name never crosses an agent boundary.
export function foldActivity(activity: AgentActivityPayload[]): TraceStep[] {
  const steps: TraceStep[] = []
  for (const a of activity) {
    const key = `${a.agent}-${a.seq}`
    switch (a.kind) {
      case 'tool_call':
        steps.push({ key, kind: 'tool', label: a.label, tool: a.tool, source: a.source, status: 'pending' })
        break
      case 'tool_result': {
        let matched = false
        for (let i = steps.length - 1; i >= 0; i--) {
          if (steps[i].kind === 'tool' && steps[i].status === 'pending' && steps[i].tool === a.tool) {
            steps[i] = { ...steps[i], detail: a.detail, status: a.status ?? 'ok' }
            matched = true
            break
          }
        }
        if (!matched) {
          steps.push({ key, kind: 'tool', label: a.label, tool: a.tool, source: a.source, detail: a.detail, status: a.status ?? 'ok' })
        }
        break
      }
      case 'done':
        steps.push({ key, kind: 'done', label: a.label, source: a.source, status: 'info' })
        break
      case 'error':
        steps.push({ key, kind: 'error', label: a.label, source: a.source, detail: a.detail, status: 'error' })
        break
      case 'thinking':
        steps.push({ key, kind: 'thinking', label: a.label, status: 'info' })
        break
    }
  }
  return steps
}

export function InvestigationTracePanel({ activity, busy, hasChain }: InvestigationTracePanelProps) {
  const steps = foldActivity(activity)

  return (
    <div className="trace-panel">
      <p className="trace-disclaimer">
        AI-generated by Claude (Sonnet 4.6). Verify findings before acting.
      </p>
      {steps.length === 0 ? (
        <div className="trace-empty">
          {!hasChain
            ? 'Waiting for chain extraction...'
            : busy
              ? 'Agents starting investigation...'
              : 'No agent activity for this incident.'}
        </div>
      ) : (
        <ol className="trace-feed">
          {steps.map((s) => (
            <li key={s.key} className={`trace-step trace-step-${s.status} trace-step-kind-${s.kind}`}>
              <div className="trace-step-head">
                {s.source && <span className="trace-source">{s.source}</span>}
                <span className="trace-label">{s.label}</span>
                {s.status === 'pending' && <span className="trace-spinner" aria-label="working" />}
              </div>
              {s.detail && <div className="trace-detail">{s.detail}</div>}
            </li>
          ))}
        </ol>
      )}
      {busy && steps.length > 0 && <div className="trace-busy">Agents still working...</div>}
    </div>
  )
}
