[domain_controllers]
dc01 ansible_host=192.168.56.10

[workstations]
ws01 ansible_host=192.168.56.11

[windows:children]
domain_controllers
workstations

[windows:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_port=5985
